export default {
  FETCH_REQUEST: "FETCH_MATCH_INVITE_REQUEST",
  FETCH_SUCCESS: "FETCH_MATCH_INVITE_SUCCESS",
  FETCH_FAILURE: "FETCH_MATCH_INVITE_FAILURE",
  CREATE_REQUEST: "CREATE_MATCH_INVITE_REQUEST",
  CREATE_SUCCESS: "CREATE_MATCH_INVITE_SUCCESS",
  CREATE_FAILURE: "CREATE_MATCH_INVITE_FAILURE",
  DELETE_REQUEST: "DELETE_MATCH_INVITE_REQUEST",
  DELETE_SUCCESS: "DELETE_MATCH_INVITE_SUCCESS",
  DELETE_FAILURE: "DELETE_MATCH_INVITE_FAILURE",
};
