export const FETCH_UFS_REQUEST = "FETCH_UFS_REQUEST";
export const FETCH_UFS_SUCCESS = "FETCH_UFS_SUCCESS";
export const FETCH_UFS_FAILURE = "FETCH_UFS_FAILURE";
export const FETCH_CITIES_REQUEST = "FETCH_CITIES_REQUEST";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "FETCH_CITIES_FAILURE";
