export default {
  CLEAR_STORE: "CLEAR_EVENT_STORE",
  FETCH_REQUEST: "FETCH_EVENT_REQUEST",
  FETCH_SUCCESS: "FETCH_EVENT_SUCCESS",
  FETCH_FAILURE: "FETCH_EVENT_FAILURE",
  CREATE_REQUEST: "CREATE_EVENT_REQUEST",
  CREATE_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_FAILURE: "CREATE_EVENT_FAILURE",
  DELETE_REQUEST: "DELETE_EVENT_REQUEST",
  DELETE_SUCCESS: "DELETE_EVENT_SUCCESS",
  DELETE_FAILURE: "DELETE_EVENT_FAILURE",
  UPDATE_REQUEST: "UPDATE_EVENT_REQUEST",
  UPDATE_SUCCESS: "UPDATE_EVENT_SUCCESS",
  UPDATE_FAILURE: "UPDATE_EVENT_FAILURE",
  FETCH_ALL_REQUEST: "FETCH_ALL_EVENT_REQUEST",
  FETCH_ALL_SUCCESS: "FETCH_ALL_EVENT_SUCCESS",
  FETCH_ALL_FAILURE: "FETCH_ALL_EVENT_FAILURE"
};
