export default {
  CREATE_REQUEST: "CREATE_MATCH_EVENT_REQUEST",
  CREATE_SUCCESS: "CREATE_MATCH_EVENT_SUCCESS",
  CREATE_FAILURE: "CREATE_MATCH_EVENT_FAILURE",
  DELETE_REQUEST: "DELETE_MATCH_EVENT_REQUEST",
  DELETE_SUCCESS: "DELETE_MATCH_EVENT_SUCCESS",
  DELETE_FAILURE: "DELETE_MATCH_EVENT_FAILURE",
  UPDATE_REQUEST: "UPDATE_MATCH_EVENT_REQUEST",
  UPDATE_SUCCESS: "UPDATE_MATCH_EVENT_SUCCESS",
  UPDATE_FAILURE: "UPDATE_MATCH_EVENT_FAILURE",
  CLEAR_STORE: "CLEAR_MATCH_EVENT_STORE"
};
