export default {
  CREATE_REQUEST: "CREATE_MATCH_ESCALATION_REQUEST",
  CREATE_SUCCESS: "CREATE_MATCH_ESCALATION_SUCCESS",
  CREATE_FAILURE: "CREATE_MATCH_ESCALATION_FAILURE",
  DELETE_REQUEST: "DELETE_MATCH_ESCALATION_REQUEST",
  DELETE_SUCCESS: "DELETE_MATCH_ESCALATION_SUCCESS",
  DELETE_FAILURE: "DELETE_MATCH_ESCALATION_FAILURE",
  UPDATE_REQUEST: "UPDATE_MATCH_ESCALATION_REQUEST",
  UPDATE_SUCCESS: "UPDATE_MATCH_ESCALATION_SUCCESS",
  UPDATE_FAILURE: "UPDATE_MATCH_ESCALATION_FAILURE",
  CLEAR_STORE: "CLEAR_MATCH_ESCALATION_STORE"
};
