export const FETCH_REQUEST = "FETCH_SESSION_REQUEST";
export const FETCH_SUCCESS = "FETCH_SESSION_SUCCESS";
export const FETCH_FAILURE = "FETCH_SESSION_FAILURE";
export const CREATE_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_FAILURE = "CREATE_SESSION_FAILURE";
