export default {
  FETCH_REQUEST: "FETCH_SEASON_REQUEST",
  FETCH_SUCCESS: "FETCH_SEASON_SUCCESS",
  FETCH_FAILURE: "FETCH_SEASON_FAILURE",
  CREATE_REQUEST: "CREATE_SEASON_REQUEST",
  CREATE_SUCCESS: "CREATE_SEASON_SUCCESS",
  CREATE_FAILURE: "CREATE_SEASON_FAILURE",
  DELETE_REQUEST: "DELETE_SEASON_REQUEST",
  DELETE_SUCCESS: "DELETE_SEASON_SUCCESS",
  DELETE_FAILURE: "DELETE_SEASON_FAILURE",
};
