export default {
  FETCH_LIST_REQUEST: "FETCH_MATCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS: "FETCH_MATCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "FETCH_MATCH_LIST_FAILURE",
  FETCH_ONE_REQUEST: "FETCH_ONE_MATCH_REQUEST",
  FETCH_ONE_SUCCESS: "FETCH_ONE_MATCH_SUCCESS",
  FETCH_ONE_FAILURE: "FETCH_ONE_MATCH_FAILURE",
  CREATE_REQUEST: "CREATE_MATCH_REQUEST",
  CREATE_SUCCESS: "CREATE_MATCH_SUCCESS",
  CREATE_FAILURE: "CREATE_MATCH_FAILURE",
  DELETE_REQUEST: "DELETE_MATCH_REQUEST",
  DELETE_SUCCESS: "DELETE_MATCH_SUCCESS",
  DELETE_FAILURE: "DELETE_MATCH_FAILURE",
  UPDATE_REQUEST: "UPDATE_MATCH_REQUEST",
  UPDATE_SUCCESS: "UPDATE_MATCH_SUCCESS",
  UPDATE_FAILURE: "UPDATE_MATCH_FAILURE",
  CLEAR_STORE: "CLEAR_MATCH_STORE"
};
